export enum EPath {
  HOME = 'home',
  SEARCH = 'find',
  BRANDS = 'brands',
  FAVORITE = 'favourite',
  ACCOUNT = 'account',
  PARENTHOME = 'ThesisHome',
  SIGNIN = 'SignIn',
  REGISTER = 'Register',
  ALLITEMS = 'AllItems',
  ITEMDETAILS = 'ItemDetails',
  SHOPPINGBAG = 'ShoppingBag',
  FORGOTPASSWORD = 'ForgotPassword',
  SIZEGUIDE = 'SizeGuide',
  CHECKOUT = 'Checkout',
  DELIVERY_ADDRESS = 'DeliveryAddress',
  DELIVERY_METHOD = 'DeliveryMethod',
  PAYMENT = 'Payment',
}
