import {EItemType} from '../../shared/models/enums/itemType.enum';
import {ESize} from '../../shared/models/enums/size.enum';
import image1 from '../../../assets/photos_without_duplicates/dresses_1_120.png';
import image2 from '../../../assets/photos_without_duplicates/dresses_2_15.png';
import image3 from '../../../assets/photos_without_duplicates/dresses_1_61.png';
import image4 from '../../../assets/photos_without_duplicates/dresses_1_62.png';
import image5 from '../../../assets/photos_without_duplicates/dresses_2_26.png';
import image6 from '../../../assets/photos_without_duplicates/dresses_2_97.png';
import image7 from '../../../assets/photos_without_duplicates/dresses_2_107.png';

import image21 from '../../../assets/photos_without_duplicates/activewear_1_24.png';
import image22 from '../../../assets/photos_without_duplicates/two_piece_outfit_2_66.png';
import image23 from '../../../assets/photos_without_duplicates/activewear_1_53.png';
import image24 from '../../../assets/photos_without_duplicates/intimates_1_53.png';
import image25 from '../../../assets/photos_without_duplicates/tops_1_35.png';
import image26 from '../../../assets/photos_without_duplicates/tops_2_72.png';
import image27 from '../../../assets/photos_without_duplicates/tops_2_65.png';

export const recommendedDataList = [
  {
    id: 91,
    season: 'New Season',
    brand: 'Heritage',
    price: 400,
    count: 0,
    keyWord: 'dress',
    description: 'Louis Vuitton',
    image: image2,
    type: EItemType.CLOTHING,
    size: ESize.ONE_SIZE,
    isHearted: false,
    imagesArray: [
      {
        id: 1,
        image: image1,
        description: 'Louis Vuitton',
        price: 1200,
      },
      {
        id: 92,
        image: image3,
        description: 'Prada',
        price: 1200,
      },
      {
        id: 93,
        image: image4,
        description: 'Chanel',
        price: 1200,
      },
      {
        id: 94,
        image: image5,
        description: 'Gucci',
        price: 1200,
      },
      {
        id: 95,
        image: image6,
        description: 'Prada',
        price: 400,
      },
      {
        id: 96,
        image: image7,
        description: 'LV',
        price: 400,
      },
    ],
  },
  {
    id: 92,
    season: 'Season',
    brand: 'Her',
    price: 400,
    count: 0,
    keyWord: 'dress',
    description: 'Prada',
    image: image3,
    type: EItemType.CLOTHING,
    size: ESize.ONE_SIZE,
    isHearted: false,
    imagesArray: [
      {
        id: 1,
        image: image1,
        description: 'Louis Vuitton',
        price: 1200,
      },
      {
        id: 92,
        image: image3,
        description: 'Prada',
        price: 1200,
      },
      {
        id: 93,
        image: image4,
        description: 'Chanel',
        price: 1200,
      },
      {
        id: 94,
        image: image5,
        description: 'Gucci',
        price: 1200,
      },
      {
        id: 95,
        image: image6,
        description: 'Prada',
        price: 400,
      },
      {
        id: 96,
        image: image7,
        description: 'LV',
        price: 400,
      },
    ],
  },
  {
    id: 93,
    season: 'New',
    brand: 'Hage',
    price: 400,
    count: 0,
    keyWord: 'dress',
    description: 'Chanel',
    image: image4,
    type: EItemType.CLOTHING,
    size: ESize.ONE_SIZE,
    isHearted: false,
    imagesArray: [
      {
        id: 1,
        image: image1,
        description: 'Louis Vuitton',
        price: 1200,
      },
      {
        id: 92,
        image: image3,
        description: 'Prada',
        price: 1200,
      },
      {
        id: 93,
        image: image4,
        description: 'Chanel',
        price: 1200,
      },
      {
        id: 94,
        image: image5,
        description: 'Gucci',
        price: 1200,
      },
      {
        id: 95,
        image: image6,
        description: 'Prada',
        price: 400,
      },
      {
        id: 96,
        image: image7,
        description: 'LV',
        price: 400,
      },
    ],
  },
  {
    id: 94,
    season: 'Nen',
    brand: 'Heage',
    price: 400,
    count: 0,
    keyWord: 'dress',
    description: 'Gucci',
    image: image5,
    type: EItemType.CLOTHING,
    size: ESize.ONE_SIZE,
    isHearted: false,
    imagesArray: [
      {
        id: 1,
        image: image1,
        description: 'Louis Vuitton',
        price: 1200,
      },
      {
        id: 92,
        image: image3,
        description: 'Prada',
        price: 1200,
      },
      {
        id: 93,
        image: image4,
        description: 'Chanel',
        price: 1200,
      },
      {
        id: 94,
        image: image5,
        description: 'Gucci',
        price: 1200,
      },
      {
        id: 95,
        image: image6,
        description: 'Prada',
        price: 400,
      },
      {
        id: 96,
        image: image7,
        description: 'LV',
        price: 400,
      },
    ],
  },
  {
    id: 95,
    season: 'ason',
    brand: 'Hge',
    price: 400,
    count: 0,
    keyWord: 'dress',
    description: 'Prada',
    image: image6,
    type: EItemType.CLOTHING,
    size: ESize.ONE_SIZE,
    isHearted: false,
    imagesArray: [
      {
        id: 1,
        image: image1,
        description: 'Louis Vuitton',
        price: 1200,
      },
      {
        id: 92,
        image: image3,
        description: 'Prada',
        price: 1200,
      },
      {
        id: 93,
        image: image4,
        description: 'Chanel',
        price: 1200,
      },
      {
        id: 94,
        image: image5,
        description: 'Gucci',
        price: 1200,
      },
      {
        id: 95,
        image: image6,
        description: 'Prada',
        price: 400,
      },
      {
        id: 96,
        image: image7,
        description: 'LV',
        price: 400,
      },
    ],
  },
  {
    id: 96,
    season: 'New Sea',
    brand: 'Herita',
    count: 0,
    keyWord: 'dress',
    description: 'LV',
    image: image7,
    type: EItemType.CLOTHING,
    size: ESize.ONE_SIZE,
    isHearted: false,
    imagesArray: [
      {
        id: 1,
        image: image1,
        description: 'Louis Vuitton',
        price: 1200,
      },
      {
        id: 92,
        image: image3,
        description: 'Prada',
        price: 1200,
      },
      {
        id: 93,
        image: image4,
        description: 'Chanel',
        price: 1200,
      },
      {
        id: 94,
        image: image5,
        description: 'Gucci',
        price: 1200,
      },
      {
        id: 95,
        image: image6,
        description: 'Prada',
        price: 400,
      },
      {
        id: 96,
        image: image7,
        description: 'LV',
        price: 400,
      },
    ],
  },
  {
    id: 98,
    season: '',
    brand: 'Pregomesh',
    price: 200,
    count: 0,
    keyWord: 'top',
    description: 'Louis Vuitton',
    image: image22,
    type: EItemType.CLOTHING,
    size: ESize.ONE_SIZE,
    isHearted: false,
    imagesArray: [
      {
        id: 2,
        image: image21,
        description: 'Louis Vuitton',
        price: 1200,
      },
      {
        id: 45,
        image: image23,
        description: 'Gucci',
        price: 210,
      },
      {
        id: 46,
        image: image24,
        description: 'Louis Vuitton',
        price: 1200,
      },
      {
        id: 47,
        image: image25,
        description: 'Chanel',
        price: 210,
      },
      {
        id: 48,
        image: image26,
        description: 'Louis Vuitton',
        price: 1200,
      },
      {
        id: 49,
        image: image27,
        description: 'Versace',
        price: 210,
      },
    ],
  },
  {
    id: 45,
    season: '',
    brand: 'Pregomesh',
    price: 200,
    count: 0,
    keyWord: 'top',
    description: 'Gucci',
    image: image23,
    type: EItemType.CLOTHING,
    size: ESize.ONE_SIZE,
    isHearted: false,
    imagesArray: [
      {
        id: 2,
        image: image21,
        description: 'Louis Vuitton',
        price: 1200,
      },
      {
        id: 45,
        image: image23,
        description: 'Gucci',
        price: 210,
      },
      {
        id: 46,
        image: image24,
        description: 'Louis Vuitton',
        price: 1200,
      },
      {
        id: 47,
        image: image25,
        description: 'Chanel',
        price: 210,
      },
      {
        id: 48,
        image: image26,
        description: 'Louis Vuitton',
        price: 1200,
      },
      {
        id: 49,
        image: image27,
        description: 'Versace',
        price: 210,
      },
    ],
  },
  {
    id: 46,
    season: '',
    brand: 'Pregomesh',
    price: 200,
    count: 0,
    keyWord: 'top',
    description: 'Louis Vuitton',
    image: image24,
    type: EItemType.CLOTHING,
    size: ESize.ONE_SIZE,
    isHearted: false,
    imagesArray: [
      {
        id: 2,
        image: image21,
        description: 'Louis Vuitton',
        price: 1200,
      },
      {
        id: 45,
        image: image23,
        description: 'Gucci',
        price: 210,
      },
      {
        id: 46,
        image: image24,
        description: 'Louis Vuitton',
        price: 1200,
      },
      {
        id: 47,
        image: image25,
        description: 'Chanel',
        price: 210,
      },
      {
        id: 48,
        image: image26,
        description: 'Louis Vuitton',
        price: 1200,
      },
      {
        id: 49,
        image: image27,
        description: 'Versace',
        price: 210,
      },
    ],
  },

  {
    id: 47,
    season: '',
    brand: 'Pregomesh',
    price: 200,
    count: 0,
    keyWord: 'top',
    description: 'Chanel',
    image: image25,
    type: EItemType.CLOTHING,
    size: ESize.ONE_SIZE,
    isHearted: false,
    imagesArray: [
      {
        id: 2,
        image: image21,
        description: 'Louis Vuitton',
        price: 1200,
      },
      {
        id: 45,
        image: image23,
        description: 'Gucci',
        price: 210,
      },
      {
        id: 46,
        image: image24,
        description: 'Louis Vuitton',
        price: 1200,
      },
      {
        id: 47,
        image: image25,
        description: 'Chanel',
        price: 210,
      },
      {
        id: 48,
        image: image26,
        description: 'Louis Vuitton',
        price: 1200,
      },
      {
        id: 49,
        image: image27,
        description: 'Versace',
        price: 210,
      },
    ],
  },
  {
    id: 48,
    season: '',
    brand: 'Pregomesh',
    price: 200,
    count: 0,
    keyWord: 'top',
    description: 'Louis Vuitton',
    image: image26,
    type: EItemType.CLOTHING,
    size: ESize.ONE_SIZE,
    isHearted: false,
    imagesArray: [
      {
        id: 2,
        image: image21,
        description: 'Louis Vuitton',
        price: 1200,
      },
      {
        id: 45,
        image: image23,
        description: 'Gucci',
        price: 210,
      },
      {
        id: 46,
        image: image24,
        description: 'Louis Vuitton',
        price: 1200,
      },
      {
        id: 47,
        image: image25,
        description: 'Chanel',
        price: 210,
      },
      {
        id: 48,
        image: image26,
        description: 'Louis Vuitton',
        price: 1200,
      },
      {
        id: 49,
        image: image27,
        description: 'Versace',
        price: 210,
      },
    ],
  },
  {
    id: 49,
    season: '',
    brand: 'Pregomesh',
    price: 200,
    count: 0,
    keyWord: 'top',
    description: 'Versace',
    image: image27,
    type: EItemType.CLOTHING,
    size: ESize.ONE_SIZE,
    isHearted: false,
    imagesArray: [
      {
        id: 2,
        image: image21,
        description: 'Louis Vuitton',
        price: 1200,
      },
      {
        id: 45,
        image: image23,
        description: 'Gucci',
        price: 210,
      },
      {
        id: 46,
        image: image24,
        description: 'Louis Vuitton',
        price: 1200,
      },
      {
        id: 47,
        image: image25,
        description: 'Chanel',
        price: 210,
      },
      {
        id: 48,
        image: image26,
        description: 'Louis Vuitton',
        price: 1200,
      },
      {
        id: 49,
        image: image27,
        description: 'Versace',
        price: 210,
      },
    ],
  },
];
